import { config } from '../../config.js';
import { buildGreenWindowPrompt } from './prompt.js';
import { callGemmaApi, extractJsonFromResponse } from './gemmaApi.js';
import { callOllama } from './ollama.js';
import {
  evaluateSafetyGuardrails,
  validateAndCorrectPlan,
  MEDICAL_DISCLAIMER_EN,
  MEDICAL_DISCLAIMER_BN
} from '../guardrails.js';
import {
  DHAKA_PREGENERATED_PLAN_EN,
  DHAKA_PREGENERATED_PLAN_BN
} from '../demoData.js';

/**
 * Main LLM Generation Router
 * Adapts between Google AI Studio Gemma API, Local Ollama, or deterministic Mock
 */
export async function generateGreenPlan({
  minutes = 30,
  goal = 'calm',
  language = 'en',
  weatherSummary,
  bestWindow,
  greenSpaces = []
}) {
  const guardrails = evaluateSafetyGuardrails({
    aqi: weatherSummary.aqi,
    apparentTemp: weatherSummary.apparentTemp,
    humidity: weatherSummary.humidity,
    precipProb: weatherSummary.precipProb,
    precip: weatherSummary.precip,
    weatherCode: weatherSummary.weatherCode,
    hour: new Date().getHours()
  });

  const prompt = buildGreenWindowPrompt({
    minutes,
    goal,
    language,
    weatherSummary,
    bestWindow,
    greenSpaces,
    guardrails
  });

  let rawPlan = null;
  let providerUsed = config.llmProvider;

  // 1. Try configured LLM provider
  if (config.llmProvider === 'gemma_api' && config.gemmaApiKey) {
    try {
      rawPlan = await callGemmaApi({
        apiKey: config.gemmaApiKey,
        model: config.gemmaModel,
        prompt
      });
      providerUsed = `gemma_api (${config.gemmaModel})`;
    } catch (err) {
      console.warn('[LLM Adapter] Gemma API call failed:', err.message, '— falling back to local/mock.');
    }
  } else if (config.llmProvider === 'ollama') {
    try {
      rawPlan = await callOllama({
        ollamaUrl: config.ollamaUrl,
        model: config.ollamaModel,
        prompt
      });
      providerUsed = `ollama (${config.ollamaModel})`;
    } catch (err) {
      console.warn('[LLM Adapter] Ollama call failed:', err.message, '— falling back to mock.');
    }
  }

  // 2. Deterministic Fallback if LLM provider was unavailable or failed
  if (!rawPlan) {
    providerUsed = 'deterministic_template';
    const basePlan = language === 'bn' ? DHAKA_PREGENERATED_PLAN_BN : DHAKA_PREGENERATED_PLAN_EN;
    const chosenSpace = greenSpaces[0] || { id: 'local_park', name: 'Community Green Space', nameBn: 'স্থানীয় পার্ক' };

    rawPlan = JSON.parse(JSON.stringify(basePlan));
    rawPlan.destination_id = chosenSpace.id;
    rawPlan.destination_name = language === 'bn' ? (chosenSpace.nameBn || chosenSpace.name) : chosenSpace.name;
    if (bestWindow) {
      rawPlan.window = {
        start: bestWindow.start?.includes('T') ? bestWindow.start.split('T')[1].slice(0, 5) : '16:30',
        end: bestWindow.end?.includes('T') ? bestWindow.end.split('T')[1].slice(0, 5) : '17:30',
        why: language === 'bn' ? (bestWindow.reasonsBn?.[0] || 'অনুকূল সবুজ ঘণ্টা') : (bestWindow.reasonsEn?.[0] || 'Optimal green window')
      };
    }
  }

  // 3. Immutable Safety Guardrails Enforcement
  // Gemma CANNOT override safety thresholds: force validate and correct
  const safePlan = validateAndCorrectPlan(rawPlan, guardrails, language);

  return {
    ...safePlan,
    _meta: {
      provider: providerUsed,
      guardrailFlags: guardrails.flags,
      generatedAt: new Date().toISOString()
    }
  };
}

/**
 * Describes a Nature Journal photograph using Gemma Multimodal or respectful fallback
 */
export async function describeNaturePhoto({
  imageBase64,
  mimeType = 'image/jpeg',
  userNote = '',
  language = 'en'
}) {
  const isBn = language === 'bn';
  const disclaimerEn = 'Disclaimer: Species identification was generated by an open AI model and might be incorrect. Always verify with local botanical field guides.';
  const disclaimerBn = 'সতর্কতা: উদ্ভিদের বা পাখির এই বিবরণটি কৃত্রিম বুদ্ধিমত্তা দ্বারা প্রস্তুত এবং ভুল হতে পারে। নিশ্চিত হতে স্থানীয় উদ্ভিদবিজ্ঞান নির্দেশিকা দেখুন।';

  if (config.gemmaApiKey && imageBase64 && config.gemmaModel.includes('gemma-3')) {
    try {
      const cleanBase64 = imageBase64.replace(/^data:image\/[a-z]+;base64,/, '');
      const prompt = `You are a mindful naturalist assistant. Describe what you observe in this nature photo (e.g., leaf shape, flower petals, tree bark, sunlight, or wildlife). 
Keep your response under 80 words, poetic, grounded, and observant. 
User's field note: "${userNote}".
Language: ${isBn ? 'Bengali (বাংলা)' : 'English'}.`;

      const url = `https://generativelanguage.googleapis.com/v1beta/models/${config.gemmaModel}:generateContent?key=${config.gemmaApiKey}`;
      const res = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [
            {
              role: 'user',
              parts: [
                { text: prompt },
                {
                  inline_data: {
                    mime_type: mimeType,
                    data: cleanBase64
                  }
                }
              ]
            }
          ],
          generationConfig: {
            temperature: 0.4,
            maxOutputTokens: 250
          }
        }),
        signal: AbortSignal.timeout(20000)
      });

      if (res.ok) {
        const data = await res.json();
        const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
        if (text) {
          return {
            description: text.trim(),
            disclaimer: isBn ? disclaimerBn : disclaimerEn,
            provider: config.gemmaModel
          };
        }
      }
    } catch (err) {
      console.warn('[Journal] Multimodal describe error:', err.message);
    }
  }

  // Fallback mindful note
  const fallbackDescEn = userNote
    ? `Field observation recorded: "${userNote}". An authentic moment of contact with the natural world, preserved on your personal device.`
    : 'A mindful moment captured during your Green Hour walk. The organic patterns of nature reflect quiet resilience in the city.';

  const fallbackDescBn = userNote
    ? `ফিল্ড পর্যবেক্ষণ লিপিবদ্ধ হয়েছে: "${userNote}"। প্রকৃতির সাথে আপনার খাঁটি সংযোগের একটি মুহূর্ত, যা আপনার ডিভাইসেই সুরক্ষিত রয়েছে।`
    : 'আপনার সবুজ ঘণ্টা পদচারণায় ধারণকৃত একটি স্নিগ্ধ মুহূর্ত। শহরের মাঝে প্রকৃতির এই স্বাভাবিক সৌন্দর্য প্রশান্তি বয়ে আনে।';

  return {
    description: isBn ? fallbackDescBn : fallbackDescEn,
    disclaimer: isBn ? disclaimerBn : disclaimerEn,
    provider: 'local_observer'
  };
}
